### ISSUE TITLE
Error in examples.js

### ISSUE THREAD

**Issue by derekscruggs** [use-weave/french-toast#1]
I'm working on content blvd and found an error in the examples. Currently line 16 has this:

    var a = brunch.scramble([main, main], ':');

It specifies colon as the delimiter, but the example data set uses periods, so it causes an error. I changed it to a period and it works as advertised.

    var a = brunch.scramble([main, main], '.');

**Comment by nparsons08** [comment]
Thanks for the heads up. We changed up the example data set to use colons.
